### ISSUE TITLE
Suggestions for helping beginners change parameters

### ISSUE THREAD

**Issue by Wan-G-Q** [izzuddinafif/MATLAB-GA-PSO#1]
Is it possible to label each parameter with a meaning or comment, this would be a great help for beginners to change parameters, thanks!

**Comment by izzuddinafif** [comment]
sure thing, sorry if my previous script confuses you. I wrote it for a certain project so it wasnt for general use. I'll rewrite it and make it more suitable for general use and beginner-friendly + well-documented with comments.

**Comment by Wan-G-Q** [comment]
> sure thing, sorry if my previous script confuses you. I wrote it for a certain project so it wasnt for general use. I'll rewrite it and make it more suitable for general use and beginner-friendly + well-documented with comments.

Thank you very much for your reply, if I may, I would greatly appreciate it, thank you again!
